name       : coffee
version    : 1.1.0
release    : 1
source     :
    - https://github.com/nick92/coffee/archive/1.1.0.tar.gz : b41ea69c81060483698f33e0e0735c4fa4e28589e9ecfafbe2703360d806eb1e
license    : GPL-3.0-or-later 
component  : desktop
summary    : Keep up-to-date with current news and weather with Coffee.
description: |
    Keep up-to-date with current news and weather with Coffee.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(geocode-glib-1.0) 
    - pkgconfig(json-glib-1.0) 
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
