name       : coffee
version    : 2.2.0
release    : 2
source     :
    - https://github.com/nick92/coffee/archive/2.2.0.tar.gz : 0f5bab22d6b0ec6ac2fc6da01316b58e9741debfc7457f4ae1c302b6167a685f
license    : GPL-3.0-or-later
component  : desktop
summary    : Keep up-to-date with current news and weather with Coffee.
description: |
    Keep up-to-date with current news and weather with Coffee.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libsoup-2.4)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
